/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/houseTest-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.86, 1.4, 0.65]}>
        <mesh geometry={nodes.Walls002.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Walls002_1.geometry} material={materials.floor} />
        <mesh geometry={nodes.Walls002_2.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Walls002_3.geometry} material={materials.BLACK} />
        <mesh geometry={nodes.Walls002_4.geometry} material={materials.controller_yellow} />
        <mesh geometry={nodes.Walls002_5.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Walls002_6.geometry} material={materials.controllers} />
        <mesh geometry={nodes.Walls002_7.geometry} material={materials.toybag} />
        <mesh geometry={nodes.Walls002_8.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Walls002_9.geometry} material={materials.controller_blue} />
        <mesh geometry={nodes.Walls002_10.geometry} material={materials.Material} />
        <mesh geometry={nodes.Walls002_11.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Walls002_12.geometry} material={materials.controllers_red} />
        <mesh geometry={nodes.Walls002_13.geometry} material={materials.controller_grey} />
        <mesh geometry={nodes.Walls002_14.geometry} material={materials.controller_white} />
        <mesh geometry={nodes.Walls002_15.geometry} material={materials.hulk_material} />
        <mesh geometry={nodes.Walls002_16.geometry} material={materials.orange} />
        <mesh geometry={nodes.Walls002_17.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Walls002_18.geometry} material={materials.tennis} />
        <mesh geometry={nodes.Walls002_19.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Walls002_20.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Walls002_21.geometry} material={materials.AIRPLANE_YELLOW} />
        <mesh geometry={nodes.Walls002_22.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Walls002_23.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Walls002_24.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Walls002_25.geometry} material={materials['Material.015']} />
      </group>
      <mesh geometry={nodes.image1.geometry} material={materials.image1} position={[1.77, 2.11, -0.13]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.16, 1.13, 1.13]} />
    </group>
  )
}

useGLTF.preload('/houseTest-transformed.glb')
