/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/House-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Text001" geometry={nodes.Text001.geometry} material={materials.BLACK} position={[1.28, 0.7, -1.87]} rotation={[1.52, 0.18, 1.39]} scale={[0.16, 0.21, 0.16]} />
        <mesh name="Text" geometry={nodes.Text.geometry} material={nodes.Text.material} position={[1.31, 1.8, 1.8]} rotation={[0, -1.29, 0]} scale={0.07} />
        <mesh name="Text002" geometry={nodes.Text002.geometry} material={materials.controller_white} position={[1.35, 1.21, -0.03]} rotation={[Math.PI, -0.03, Math.PI / 2]} scale={0.09} />
        <mesh name="Text003" geometry={nodes.Text003.geometry} material={materials.controller_yellow} position={[1.35, 1.08, -0.44]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.09} />
        <mesh name="Text004" geometry={nodes.Text004.geometry} material={nodes.Text004.material} position={[1.35, 1.02, -0.43]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.06} />
        <mesh name="Text005" geometry={nodes.Text005.geometry} material={materials.controller_white} position={[1.37, 0.95, -0.39]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.05} />
        <mesh name="Text006" geometry={nodes.Text006.geometry} material={materials.controller_white} position={[-2.94, 3.44, -2.29]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="Text007" geometry={nodes.Text007.geometry} material={materials.controller_white} position={[-3.09, 3.09, -2.27]} rotation={[Math.PI / 2, 0, 0]} scale={0.29} />
        <group name="Plane001" position={[-0.86, 1.4, 0.65]}>
          <mesh name="Walls" geometry={nodes.Walls.geometry} material={materials['Material.003']} />
          <mesh name="Walls_1" geometry={nodes.Walls_1.geometry} material={materials.floor} />
          <mesh name="Walls_2" geometry={nodes.Walls_2.geometry} material={materials['Material.013']} />
          <mesh name="Walls_3" geometry={nodes.Walls_3.geometry} material={materials.BLACK} />
          <mesh name="Walls_4" geometry={nodes.Walls_4.geometry} material={materials.controller_yellow} />
          <mesh name="Walls_5" geometry={nodes.Walls_5.geometry} material={materials['Material.004']} />
          <mesh name="Walls_6" geometry={nodes.Walls_6.geometry} material={materials.controllers} />
          <mesh name="Walls_7" geometry={nodes.Walls_7.geometry} material={materials['Material.005']} />
          <mesh name="Walls_8" geometry={nodes.Walls_8.geometry} material={materials['Material.002']} />
          <mesh name="Walls_9" geometry={nodes.Walls_9.geometry} material={materials.computer_stance} />
          <mesh name="Walls_10" geometry={nodes.Walls_10.geometry} material={materials.controller_blue} />
          <mesh name="Walls_11" geometry={nodes.Walls_11.geometry} material={materials.Material} />
          <mesh name="Walls_12" geometry={nodes.Walls_12.geometry} material={materials['Material.001']} />
          <mesh name="Walls_13" geometry={nodes.Walls_13.geometry} material={materials.controllers_red} />
          <mesh name="Walls_14" geometry={nodes.Walls_14.geometry} material={materials.controller_grey} />
          <mesh name="Walls_15" geometry={nodes.Walls_15.geometry} material={materials.controller_white} />
          <mesh name="Walls_16" geometry={nodes.Walls_16.geometry} material={materials.hulk_material} />
          <mesh name="Walls_17" geometry={nodes.Walls_17.geometry} material={materials.orange} />
          <mesh name="Walls_18" geometry={nodes.Walls_18.geometry} material={materials['Material.007']} />
          <mesh name="Walls_19" geometry={nodes.Walls_19.geometry} material={materials['Material.008']} />
          <mesh name="Walls_20" geometry={nodes.Walls_20.geometry} material={materials.poke_pika} />
          <mesh name="Walls_21" geometry={nodes.Walls_21.geometry} material={materials['Material.006']} />
          <mesh name="Walls_22" geometry={nodes.Walls_22.geometry} material={materials['Material.010']} />
          <mesh name="Walls_23" geometry={nodes.Walls_23.geometry} material={materials.AIRPLANE_YELLOW} />
          <mesh name="Walls_24" geometry={nodes.Walls_24.geometry} material={materials['Material.009']} />
          <mesh name="Walls_25" geometry={nodes.Walls_25.geometry} material={materials['Material.011']} />
          <mesh name="Walls_26" geometry={nodes.Walls_26.geometry} material={materials['1_sMryEXZVPKFjGNcfSzE8Mw']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/House-transformed.glb')