/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/WORLD2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[1.49, 1.39, 0.25]} rotation={[1.41, -0.09, -1.59]} />
      <mesh geometry={nodes.Sphere008.geometry} material={nodes.Sphere008.material} position={[16.05, 0.61, -1.5]} />
      <mesh geometry={nodes.Sphere009.geometry} material={nodes.Sphere009.material} position={[15.91, 0.58, -1.5]} rotation={[0, 0.88, 0]} />
      <mesh geometry={nodes.Sphere010.geometry} material={nodes.Sphere010.material} position={[15.91, 0.68, -0.87]} rotation={[0, 1.05, 0]} />
      <mesh geometry={nodes.Sphere011.geometry} material={nodes.Sphere011.material} position={[16.76, 0.49, -1.5]} rotation={[0.05, 0.05, -0.1]} />
      <mesh geometry={nodes.Sphere012.geometry} material={nodes.Sphere012.material} position={[17.25, 0.62, -1.28]} rotation={[0.01, 0, -0.02]} />
      <mesh geometry={nodes.Circle.geometry} material={nodes.Circle.material} position={[14.74, 5.56, -0.47]} rotation={[1.93, 0.2, -2.65]} />
      <mesh geometry={nodes.Icosphere.geometry} material={nodes.Icosphere.material} position={[-8.42, 0.87, -5.02]} rotation={[2.57, 1.06, 0.15]} />
      <mesh geometry={nodes.Cylinder021.geometry} material={nodes.Cylinder021.material} position={[-8.18, 0.32, -4.73]} rotation={[1.18, 0.02, 1.21]} />
      <mesh geometry={nodes.Cylinder022.geometry} material={nodes.Cylinder022.material} position={[-8.18, 0.31, -4.73]} rotation={[1.29, 0.28, 0.49]} />
      <mesh geometry={nodes.Cylinder023.geometry} material={nodes.Cylinder023.material} position={[-7.98, 0.31, -4.95]} rotation={[1.45, 0.37, 0]} />
      <mesh geometry={nodes.Cylinder024.geometry} material={nodes.Cylinder024.material} position={[-8.11, 0.51, -5.38]} rotation={[1.98, 0.64, -0.92]} />
      <mesh geometry={nodes.Cylinder025.geometry} material={nodes.Cylinder025.material} position={[-8.23, 0.33, -5.25]} rotation={[1.94, 0.13, -1.55]} />
      <mesh geometry={nodes.rock048.geometry} material={nodes.rock048.material} position={[-8.37, 0.79, -5.42]} rotation={[0, 1.05, 0]} />
      <mesh geometry={nodes.rock050.geometry} material={nodes.rock050.material} position={[-8.17, 0.79, -5.27]} rotation={[-0.09, 0.67, 0.76]} />
      <mesh geometry={nodes.rock051.geometry} material={nodes.rock051.material} position={[-8.66, 0.79, -5.11]} rotation={[0.22, 0.88, 0.14]} />
      <mesh geometry={nodes.Circle017.geometry} material={nodes.Circle017.material} position={[-2.01, 5.3, 1.31]} rotation={[1.77, -0.01, 3.11]} />
      <mesh geometry={nodes.Circle018.geometry} material={nodes.Circle018.material} position={[-2.03, 5.42, 1.04]} rotation={[1.86, -0.01, 3.12]} />
    </group>
  )
}

useGLTF.preload('/WORLD2.glb')
